### ISSUE TITLE
Not an Issue, a Thank You

### ISSUE THREAD

**Issue by sudosci** [Sciss/JCollider#2]
I just wanted to say that I recently checked out this code and within half an hour I was listening to demo synths playing to my ears' delight.  

I realize this is not an actively developed project, but I've sort of adopted it for a learning experiment (as I know Java much better than Scala.  

Many thanks for the excellent software.  Very impressed! :)

**Comment by Sciss** [comment]
You are welcome, thanks for your kind words. I'm glad the software is still useful.
